const ProfileData = [
  {
    id: 1,
    name: "Aarav Sharma",
    desc: "Software Engineer at Google",
    location: "Magarpatta",
    photo: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: 2,
    name: "Sneha Patil",
    desc: "UI/UX Designer at Infosys",
    location: "Viman Nagar",
    photo: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 3,
    name: "Rohan Deshmukh",
    desc: "Data Scientist at TCS",
    location: "Baner",
    photo: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 4,
    name: "Priya Kulkarni",
    desc: "Manager at Cognizant",
    location: "Kalyani Nagar",
    photo: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: 5,
    name: "Vikram Joshi",
    desc: "Developer at Wipro",
    location: "Hadapsar",
    photo: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 6,
    name: "Anjali Nair",
    desc: "HR Manager at Capgemini",
    location: "Fergusson College Road",
    photo: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 7,
    name: "Raj Malhotra",
    desc: "Developer at Tech Mahindra",
    location: "Aundh",
    photo: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: 8,
    name: "Kavya Iyer",
    desc: "Marketing Lead at Zensar",
    location: "Deccan Gymkhana",
    photo: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    id: 9,
    name: "Amit Trivedi",
    desc: "Engineer at Persistent",
    location: "Pimple Saudagar",
    photo: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    id: 10,
    name: "Neha Mehta",
    desc: "Cloud Architect at IBM",
    location: "Wakad",
    photo: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 11,
    name: "Siddharth Gupta",
    desc: "AI Engineer at Nvidia",
    location: "Pashan",
    photo: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: 12,
    name: "Divya Verma",
    desc: "Analyst at Accenture",
    location: "Vishal Nagar",
    photo: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: 13,
    name: "Kunal Kapoor",
    desc: "ML Engineer at Amazon",
    location: "Sangamwadi",
    photo: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    id: 14,
    name: "Swati Agarwal",
    desc: "Backend Developer at Infosys",
    location: "Shivajinagar",
    photo: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: 15,
    name: "Harshad Bhosale",
    desc: "AI Researcher at Microsoft",
    location: "Viman Nagar",
    photo: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: 16,
    name: "Ritika Chauhan",
    desc: "Digital Marketing Head at Flipkart",
    location: "Magarpatta",
    photo: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    id: 17,
    name: "Arjun Reddy",
    desc: "Software Architect at Oracle",
    location: "Wakad",
    photo: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: 18,
    name: "Meera Menon",
    desc: "Project Manager at Deloitte",
    location: "Aundh",
    photo: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: 19,
    name: "Dhruv Rao",
    desc: "Mobile App Developer at PhonePe",
    location: "Pimple Nilakh",
    photo: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: 20,
    name: "Sanya Gupta",
    desc: "Content Strategist at LinkedIn",
    location: "Baner",
    photo: "https://randomuser.me/api/portraits/women/19.jpg",
  },
];

export default ProfileData;
